# Generated by Django 5.1.7 on 2025-03-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashpool', '0001_initial'),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='chama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='cashpool.chama'),
        ),
    ]
