# Generated by Django 5.1.7 on 2025-03-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contribution_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('special', 'Special'), ('fine', 'Fine')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='contribution',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
