# Generated by Django 5.1.7 on 2025-04-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_contribution_confirmed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='transaction_id',
            new_name='transaction_ref',
        ),
    ]
