# Generated by Django 5.1.7 on 2025-04-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_rename_transaction_id_contribution_transaction_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='is_confirmed',
        ),
    ]
