# Generated by Django 5.1.7 on 2025-08-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_remove_contribution_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
