# Generated by Django 5.1.7 on 2025-04-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_ledgerentry_delete_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
