# Generated by Django 5.1.7 on 2025-08-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_ledgerentry_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='initiated_by',
        ),
    ]
