# Generated by Django 5.1.7 on 2025-08-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='0720000000', help_text='e.g., 254712345678', max_length=15, unique=True),
        ),
    ]
