# Generated by Django 5.1.7 on 2025-03-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
    ]
