# Generated by Django 5.1.7 on 2025-03-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashpool', '0002_chama_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chama',
            old_name='chama_name',
            new_name='name',
        ),
    ]
