# Generated by Django 5.1.7 on 2025-04-02 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashpool', '0004_cashpool_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chama',
            name='chama_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_chamas', to=settings.AUTH_USER_MODEL, verbose_name='Chairman'),
        ),
    ]
